name: porker_expected_value
description: A new Flutter application.


publish_to:

version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.5.0
  admob_flutter: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/cards/spade/
    - assets/cards/clover/
    - assets/cards/diamond/
    - assets/cards/heart/







  uses-material-design: true

